# Generated by Django 5.2.1 on 2025-05-30 17:41

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[
                 ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(
                    help_text="Candidate's email address (must be unique)", max_length=254, unique=True)),
                ('phone_number', models.CharField(
                    help_text="Candidate's phone number (must be unique)", max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='candidate_name_gin_trgm_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
